### ISSUE TITLE
support for rails 5

### ISSUE THREAD

**Issue by jpaas** [ermolaev/rails_string_enum#1]
Rails 5 is going to hit rc1 real soon now but the current activerecord dependency in the rails_string_enum gemspec won't allow it to work with Rails 5. Any chance of bumping it up?

**Comment by ermolaev** [comment]
Hello, I'm released new version
dependensy "activerecord", "~> 4.2" removed, but not tested in Rails 5

Maybe you will be interested in the new functionality 
https://github.com/ermolaev/rails_string_enum#using-constants-to-any-class-or-module
